### ISSUE TITLE
Farming stats from multiple harvesters

### ISSUE THREAD

**Issue by aroysbox** [retzkek/chiamon#27]
I was able to setup everything. Great job putting this together. 

Wondering if there is a way to add stats about remote harvesters across other machines as well on the same dashboard as they connect to the farmer server.

**Comment by retzkek** [comment]
Yes, you run the appropriate exporters (node_exporter and mtail for a harvester) on each node, and add them as targets in the prometheus config, for example:

```yaml
  - job_name: 'node'
    static_configs:
      - targets: ['harvester1:9100', 'harvester2:9100']
```
also see #25.
