### ISSUE TITLE
Node Exporter Volume

### ISSUE THREAD

**Issue by felipecaldas** [retzkek/chiamon#9]
Hi guys,

Thanks for chiamon, it's pretty neat. Trying to run this on Windows and looking that docker-compose:

```
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - 'C:\:/host:ro,rslave'
```

What's the volume for the node_exporter meant to be? I can't get it to run, I get:

```
2021/05/15 12:14:16 chia_exporter version 0.2

2021/05/15 12:14:16 error calling get_network_info: Post "https://localhost:8555/get_network_info": dial tcp [::1]:8555: connect: connection refused
```
